version: '3'

networks:
  frontend:

services:
  frontend:
    container_name: frontend
    build: ./
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    network_mode: host
    #networks:
    #  - frontend
    #ports:
    #  - "5173:5173"
    restart: on-failure