# Generated by Django 5.1.3 on 2024-11-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('mesa', models.CharField(max_length=10)),
                ('comentario', models.TextField()),
                ('presente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noiva', models.CharField(max_length=100)),
                ('noivo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('lista', models.JSONField()),
                ('mensagem', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
