# Generated by Django 5.1.1 on 2024-09-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
