# Generated by Django 5.1.3 on 2024-11-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
