# Generated by Django 5.1.3 on 2024-11-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0003_alter_convidado_comentario_alter_convidado_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='lista',
        ),
        migrations.AlterField(
            model_name='evento',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
