# Generated by Django 5.1.3 on 2024-11-06 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0004_remove_evento_lista_alter_evento_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='evento',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to='server_api.evento'),
        ),
    ]
